server:
  port: 30000

spring:
  application:
    name: gulimall-third-party
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 #配置Nacos地址
    alicloud:
      access-key: 
      secret-key: 
      #对象存储
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: gulimall-isliujiao
      #短信发送
      sms:
        host: https://dfsns.market.alicloudapi.com
        path: /data/send_sms
        template_id: TPL_0000
        appcode: 

